### ISSUE TITLE
Labels that start with underscore cause problems

### ISSUE THREAD

**Issue by neuschaefer** [fox32-arch/fox32asm#11]
```
_L: jmp _L
```

Leads to:

```
Parsing file...
Error {
    variant: ParsingError {
        positives: [
            EOI,
            origin,
            include_bin,
            data,
            constant,
            label_kind,
            instruction,
        ],
        negatives: [],
    },
    location: Pos(
        9,
    ),
    line_col: Pos(
        (
            1,
            10,
        ),
    ),
    path: None,
    line: "_L: jmp _L␊",
    continued_line: None,
}
```

**Comment by ry755** [comment]
I noticed the same issue with labels that start with a number, for example `4byte_ptr`.

**Comment by neuschaefer** [comment]
Ok, it seems `pest` can't deal with this kind of abiguity: `4byte_ptr` looks like a decimal number at the start, and `_L` also used to look like a decimal number, until I required that decimal numbers start with a digit, and underscores may only occur after the first digit.
