### ISSUE TITLE
For safety: Detect duplicate defitions of labels

### ISSUE THREAD

**Issue by neuschaefer** [fox32-arch/fox32asm#2]
Currently the latest definition of a label wins, but I don't quite see a usecase where this behavior is needed, I rather think it's a safety hazard most of the time.

Therefore, I think it would be better to reject programs with duplicate label definitions (and maybe reintroduce them later with a more explicit design).

**Comment by ry755** [comment]
Fixed in b40c8d50b63c2d786a7ed1e64f903dabab991ced. This is something I've been meaning to get around to but forgot, so thanks for reminding me :3
