### ISSUE TITLE
Signed division instructions (IDIV, IREM)

### ISSUE THREAD

**Issue by neuschaefer** [fox32-arch/fox32asm#3]
The emulator [contains](https://github.com/fox32-arch/fox32/blob/main/src/cpu.c#L1029) signed versions of the DIV and REM instructions, but the assembler currently doesn't handle them. What's the right direction to resolve this inconsistency?

**Comment by ry755** [comment]
Fixed in abd160e6e58cd3edbe925941fc2569233ee08203.

**Comment by neuschaefer** [comment]
awesome, thanks
